spring:
  profiles.active: development
---
springdoc:
  swagger-ui:
    enabled: true
spring:
  servlet:
    multipart:
      max-file-size: 50MB
  config:
    activate:
      on-profile:
        - development
token:
  bearer: token
# server:
#   ssl:
#     key-store: classpath:keystore.p12
#     key-store-password: password
#     key-store-type: pkcs12
#     key-alias: springboot
#     key-password: password
#   port: 8443
  # datasource:
  #   driverClassName: org.postgresql.Driver
  #   url: jdbc:postgresql://127.0.0.1:5432/postgres
  #   username: postgres
  #   password: postgres
  # jpa:
  #   show-sql: true
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.PostgreSQLDialect
  #   hibernate:
  #     ddl-auto: create-drop
---
spring:
  config:
    activate:
      on-profile:
        - production
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${PROD_URL}:${PORT}/${DB_NAME}
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  ssl:
    key-store: ${KEY_STORE}
    key-store-password: ${PASSWORD}
    key-store-type: ${KEYSTORE_TYPE}
    key-alias: ${KEY_ALIAS}
    key-password: ${KEYPASSWORD}
  port: ${PORT}
springdoc:
  swagger-ui:
    enabled: false
